export const CZECH_BANKS = [
  { code: "0100", name: "Komerční banka" },
  { code: "0300", name: "ČSOB" },
  { code: "0600", name: "MONETA Money Bank" },
  { code: "0710", name: "Česká národní banka" },
  { code: "0800", name: "Česká spořitelna" },
  { code: "2010", name: "Fio banka" },
  { code: "2020", name: "BANK OF CHINA" },
  { code: "2060", name: "Citfin" },
  { code: "2070", name: "Moravský Peněžní Ústav" },
  { code: "2100", name: "Hypoteční banka" },
  { code: "2220", name: "Artesa" },
  { code: "2240", name: "Poštová banka" },
  { code: "2250", name: "Banka CREDITAS" },
  { code: "2260", name: "NEY spořitelní družstvo" },
  { code: "2275", name: "Podnikatelská družstevní záložna" },
  { code: "2600", name: "Citibank" },
  { code: "2700", name: "UniCredit Bank" },
  { code: "3030", name: "Air Bank" },
  { code: "3050", name: "BNP Paribas Personal Finance" },
  { code: "3060", name: "PKO BP S.A." },
  { code: "3500", name: "ING Bank" },
  { code: "4000", name: "Max banka" },
  { code: "4300", name: "Národní rozvojová banka" },
  { code: "5500", name: "Raiffeisenbank" },
  { code: "5800", name: "J&T Banka" },
  { code: "6000", name: "PPF banka" },
  { code: "6100", name: "Equa bank" },
  { code: "6200", name: "COMMERZBANK" },
  { code: "6210", name: "mBank" },
  { code: "6300", name: "BNP Paribas Cardif" },
  { code: "6700", name: "Všeobecná úverová banka" },
  { code: "6800", name: "Sberbank CZ" },
  { code: "7910", name: "Deutsche Bank" },
  { code: "7940", name: "Waldviertler Sparkasse Bank" },
  { code: "7950", name: "Raiffeisen stavební spořitelna" },
  { code: "7960", name: "ČSOB Stavební spořitelna" },
  { code: "7970", name: "Modrá pyramida stavební spořitelna" },
  { code: "7990", name: "Českomoravská stavební spořitelna" },
  { code: "8030", name: "Volksbank Raiffeisenbank Nordoberpfalz" },
  { code: "8040", name: "Oberbank AG" },
  { code: "8060", name: "Stavební spořitelna ČS" },
  { code: "8090", name: "Česká exportní banka" },
  { code: "8150", name: "HSBC Continental Europe" },
  { code: "8200", name: "PRIVAT BANK" },
  { code: "8250", name: "Bank of Communications" },
  { code: "8255", name: "Trinity Bank" },
  { code: "8260", name: "ICBC" },
  { code: "8270", name: "Fairplay Pay" },
  { code: "8280", name: "B-Efekt" },
  { code: "8292", name: "NBS" },
  { code: "8293", name: "Partner banka" },
] as const
